FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
COPY common/package.json ./common/
COPY client/package.json ./client/

RUN npm ci

COPY common ./common
COPY client ./client

RUN npm run build -w client

FROM nginx:alpine

COPY --from=builder /app/client/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
